export enum ErrorEnum {
    InvalidActiveDate = 'The start date must be lower than the end date!',
    emailExists = 'Email exists!',
    DataNotFound = 'Data not found!',
    phoneExists = 'Phone exists!',
    driverLicenseDriverExists = 'Driver license exists!',
    loginUsed = 'This login is already in use!',
    nameUsed = 'This name is already in use!',
    UserNotFound = 'User not found!',
    RoleNotFound = 'Role not found!',
    CodeIncorrectly = 'Code incorrectly!',
    fileNotFound = 'File not found!',
    token = 'token is required!',
    invalidData = 'You have send invalid data',
    errorServer = 'Internal server error!',
    equalPasswords = 'password and repeat password not equal!',
}
